In [1]:
import cv2
from matplotlib import pyplot as plt
im = cv2.imread("big.jpg")

plt.imshow(im)

## Задание 1
### Какого размера изображение? Ответ - произведение ширины на высоту.

In [2]:
import cv2
import numpy as np
im = cv2.imread("big.jpg") # return type numpy.ndarray

#print(im.shape)
#print(375*500)
im.shape[0]*im.shape[1]

187500

## Задание 2
### Найдите среднее значению по каждому из каналов. Ответ - среднее в 3 канале, округлить до целого.

In [3]:
import cv2
import numpy as np
im = cv2.imread("big.jpg") # return type numpy.ndarray

avg = im.mean(axis = (1, 0)) # np.mean(im, axis = (1, 0))
print(avg)
round(avg[2])

[ 49.91059733  92.14002667 128.69120533]


129.0

## Задача 3
### Посчитайте разброс (среднеквадратичное отклонение) значений по каждому из каналов. Ответ - разброс в 1 канале, округлить до целого.

In [4]:
sigma = np.sqrt(((im - avg)**2).mean(axis = (1, 0)))
print(sigma)
round(sigma[0])

[38.29606242 62.76430657 77.48906153]


38.0

#### или:

In [5]:
sigma = np.std(im, axis = (1, 0))
print(sigma)
round(sigma[0])

[38.29606242 62.76430657 77.48906153]


38.0

## Задача 4
### Поменяйте каналы исходного изображения в обратном порядке, какое число стоит на позиции [0,345,0]

In [6]:
rev_im = np.flip(im, axis = 2)
rev_im[0][345][0]

192

## Задача 5
### Сколько столбцов, в которых есть хоть одно значение 7?

In [7]:
# np.where?
np.random.seed(7964)
A = np.random.randint(0, 8, size=(500, 500))
res = np.count_nonzero(np.count_nonzero((A == 7), axis = 0) != 0)
res

500

## Задача 6
### Найдите индексы значений, которые меньше 4. Ответ - сумма сумм индексов строк и столбцов между собой.

In [8]:
np.sum(np.argwhere(A < 4))

62383552

## Задача 7
### Найдите индексы значений, которые меньше 4 и не меньше 2. Ответ - сумма сумм индексов строк и столбцов между собой.

In [9]:
np.sum(np.argwhere(np.all([A < 4, A >= 2], axis = 0)))

31139828

## Задача 8
### Просуммировать все значения по индексам значений из предыдущего задания.

In [10]:
condition = np.all([A < 4, A >=2], axis = 0)
np.sum(np.extract(condition, A))

156096

## Задача 9
### Найдите максимальное значение в каждом столбце массива. Ответ - сумма значений.

In [11]:
np.sum(np.max(A, axis = 0))

3500

In [12]:
x = np.arange(1, 501, 1)

## Задача 10
### Найти скалярное произведение массива A и x. Ответ - сумма значений.

In [13]:
np.sum(np.dot(A, x)) #np.sum(A*x) #np.sum(A@x) calls np.matmul

218833635

In [14]:
np.random.seed(33)
w = np.random.randint(0, 8, size=(5, 500))

## Задача 11
### Умножьте массив A на массив w транспонированный. Ответ - сумма значений.

In [15]:
np.sum(np.dot(A, w.T)) #np.sum(A @ w.T)

15215957

## Задача 12
### Умножьте массив A на массив w поэлементно. Ответ - сумма значений.

In [16]:
np.random.seed(33)
w = np.random.randint(0, 8, size=(500, 500))
np.sum(np.sum(A@w))

1530052726